"use client";
import { CacheProvider } from "@chakra-ui/next-js";
import { ChakraProvider } from "@chakra-ui/react";
import { extendTheme, withDefaultColorScheme } from "@chakra-ui/react";

const colors: object = {
  brand: {
    50: "#F2FBEF",
    100: "#E4F7DE",
    200: "#D6F3CE",
    300: "#C8EFBD",
    400: "#BAEBAD",
    500: "#5DCF3A",
    600: "#53C530",
    700: "#4CB52C",
    800: "#45A428",
    900: "#3E9424",
  },
};

export const theme = extendTheme({ colors: colors });
// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CacheProvider>
          <ChakraProvider theme={theme}>{children}</ChakraProvider>
        </CacheProvider>
      </body>
    </html>
  );
}
